name: CMake
on:
    push:
jobs:
    build-project:
        name: Build Project
        runs-on: windows-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@v4.1.7

            - name: "Install doxygen"
              uses: ssciwr/doxygen-install@v1

            - name: Build Project
              uses: threeal/cmake-action@v2.0.0
              with:
                  build-dir: build
                  generator: "Visual Studio 17 2022"
            - name: Deploy to GitHub Pages
              uses: Cecilapp/GitHub-Pages-deploy@v3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  build_dir: docs/html
                  email: cadmu661@student.otago.ac.nz
